version: '3.7'

services:
  python:
    build:
      context: ./docker/local/python
      dockerfile: ./Dockerfile
    restart: 'no'
    command: ["bash", "/run.sh"]
    volumes:
      - ./run.sh:/run.sh
      - ./src:/app
    ports:
      - "8080:8080"